# Generated by Django 4.2 on 2024-07-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Final', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='detalle',
            field=models.TextField(max_length=280),
        ),
    ]
